-- Skins
Settings.skins = {
	['Regulares'] = {
		{ model = 'a_m_y_hipster_01', name = 'Hipster 1 (M)', rank = 1 },
		{ model = 'a_f_y_hipster_01', name = 'Hipster 1 (F)', rank = 1 },
		{ model = 'a_m_y_hipster_02', name = 'Hipster 2 (M)', rank = 1 },
		{ model = 'a_f_y_hipster_02', name = 'Hipster 2 (F)', rank = 1 },
		{ model = 'a_m_y_hipster_03', name = 'Hipster 3 (M)', rank = 1 },
		{ model = 'a_f_y_hipster_03', name = 'Hipster 3 (F)', rank = 1 },
		{ model = 's_m_y_cop_01', name = 'Cop (M)', rank = 1 },
		{ model = 's_f_y_cop_01', name = 'Cop (F)', rank = 1 },
		{ model = 's_m_m_paramedic_01', name = 'Medic (M)', rank = 1 },
		{ model = 'g_m_y_ballaorig_01', name = 'Ballas 1 (M)', rank = 1 },
		{ model = 'g_m_y_ballasout_01', name = 'Ballas 2 (M)', rank = 1 },
		{ model = 'g_m_y_ballaeast_01', name = 'Ballas 3 (M)', rank = 1 },
		{ model = 'g_f_y_ballas_01', name = 'Ballas 4 (F)', rank = 1 },
		{ model = 'g_m_y_famca_01', name = 'Families 1 (M)', rank = 1 },
		{ model = 'g_m_y_famfor_01', name = 'Families 2 (M)', rank = 1 },
		{ model = 'g_m_y_famdnf_01', name = 'Families 3 (M)', rank = 1 },
		{ model = 'g_f_y_families_01', name = 'Families 4 (F)', rank = 1 },
		{ model = 'a_m_m_bevhills_01', name = 'Casual 1 (M)', rank = 1 },
		{ model = 'a_f_m_bevhills_01', name = 'Casual 1 (F)', rank = 1 },
		{ model = 'a_m_y_bevhills_01', name = 'Casual 2 (M)', rank = 1 },
		{ model = 'a_f_y_bevhills_01', name = 'Casual 2 (F)', rank = 1 },
		{ model = 'a_m_m_bevhills_02', name = 'Casual 3 (M)', rank = 1 },
		{ model = 'a_m_y_bevhills_02', name = 'Casual 4 (M)', rank = 1 },
		{ model = 'a_f_y_bevhills_03', name = 'Casual 5 (F)', rank = 1 },
		{ model = 'a_f_y_bevhills_04', name = 'Casual 6 (F)', rank = 1 },
		{ model = 'a_m_m_business_01', name = 'Businessman 1 (M)', rank = 1 },
		{ model = 'a_m_y_business_01', name = 'Businessman 2 (M)', rank = 1 },
		{ model = 'a_f_y_business_01', name = 'Businessman 2 (F)', rank = 1 },
		{ model = 'a_m_y_business_02', name = 'Businessman 3 (M)', rank = 1 },
		{ model = 'a_m_y_business_03', name = 'Businessman 4 (M)', rank = 1 },
		{ model = 'a_f_y_business_04', name = 'Businessman 5 (F)', rank = 1 },
		{ model = 'g_m_m_chigoon_01', name = 'Chigoon 1 (M)', rank = 1 },
		{ model = 'g_m_m_chigoon_02', name = 'Chigoon 2 (M)', rank = 1 },
	},

	['Desbloqueables'] = {
		{ model = 'g_m_m_chemwork_01', name = 'Chemist', rank = 10 },
		{ model = 's_m_y_fireman_01', name = 'Fireman', rank = 20 },
		{ model = 's_m_m_fibsec_01', name = 'FIB Security', rank = 30 },
		{ model = 's_m_y_clown_01', name = 'Clown', rank = 40 },
		{ model = 'u_m_y_zombie_01', name = 'Zombie', rank = 50 },
		{ model = 's_m_m_strperf_01', name = 'Street Performer', rank = 60 },
		{ model = 'u_m_y_staggrm_01', name = 'Striper', rank = 70 },
		{ model = 's_m_y_prismuscl_01', name = 'Prisionero', rank = 80 },
		{ model = 'u_m_y_rsranger_01', name = 'RS Ranger', rank = 90 },
	},

	['Prestigio'] = {
		{ model = 's_m_m_doctor_01', name = 'Doctor', prestige = 1 },
		{ model = 's_m_y_mime', name = 'Mimo', prestige = 2 },
		{ model = 'u_m_y_mani', name = 'Mexicano', prestige = 3 },
		{ model = 's_m_m_movspace_01', name = 'Astronauta', prestige = 4 },
		{ model = 'u_m_y_imporage', name = 'Imporage', prestige = 5 },
		{ model = 'u_m_m_griff_01', name = 'Griff?', prestige = 6 },
		{ model = 'u_m_y_babyd', name = 'Baby', prestige = 7 },
		{ model = 's_m_y_factory_01', name = 'Factory Man', prestige = 8 },
		{ model = 'u_m_m_jesus_01', name = 'Jesus', prestige = 9 },
		{ model = 'u_m_o_filmnoir', name = 'Zombie', prestige = 10 },
	},

	['Patreon'] = {
		{ model = 'a_m_y_dhill_01', name = 'Biker', patreonTier = 1 },
		{ model = 'a_m_m_trampbeac_01', name = 'Vagabundo', patreonTier = 1 },
		{ model = 'g_m_m_chicold_01', name = 'Atracador', patreonTier = 1 },

		{ model = 'g_m_y_lost_03', name = 'Motero', patreonTier = 2 },
		{ model = 'u_f_y_jewelass_01', name = 'China', patreonTier = 2 },
		{ model = 's_m_m_bouncer_01', name = 'Bola de nieve', patreonTier = 2 },

		{ model = 'u_m_y_pogo_01', name = 'Mono', patreonTier = 3 },
		{ model = 'u_m_y_dancerave_01', name = 'Fluo Hombre', patreonTier = 3 },
		{ model = 'u_f_y_dancerave_01', name = 'Fluo Chica', patreonTier = 3 },
		{ model = 's_m_m_movalien_01', name = 'Alien', patreonTier = 3 },
	},
}
